const quizData = [
  {
    id: 1,
    question: "What is the capital of Canada?",
    answer: "Ottawa",
    options: ["Toronto", "Montreal", "Vancouver", "Ottawa"],
    userAnswer: "",
  },
  {
    id: 2,
    question: "Which gas do plants use for photosynthesis?",
    answer: "Carbon dioxide",
    options: ["Oxygen", "Carbon monoxide", "Nitrogen", "Carbon dioxide"],
    userAnswer: "",
  },
  {
    id: 3,
    question: "What is the largest mammal?",
    answer: "Blue whale",
    options: ["Elephant", "Giraffe", "Blue whale", "Lion"],
    userAnswer: "",
  },
  {
    id: 4,
    question: "Which element has the chemical symbol 'Fe'?",
    answer: "Iron",
    options: ["Gold", "Silver", "Iron", "Copper"],
    userAnswer: "",
  },
  {
    id: 5,
    question: "What is the currency of Japan?",
    answer: "Japanese yen",
    options: ["Yuan", "Rupee", "Euro", "Japanese yen"],
    userAnswer: "",
  },
  {
    id: 6,
    question: "Who wrote the play 'Romeo and Juliet'?",
    answer: "William Shakespeare",
    options: [
      "Mark Twain",
      "Jane Austen",
      "William Shakespeare",
      "Charles Dickens",
    ],
    userAnswer: "",
  },
  {
    id: 7,
    question: "What is the capital of Australia?",
    answer: "Canberra",
    options: ["Melbourne", "Sydney", "Canberra", "Brisbane"],
    userAnswer: "",
  },
  {
    id: 8,
    question: "Which planet is known as the 'Morning Star' or 'Evening Star'?",
    answer: "Venus",
    options: ["Mars", "Venus", "Jupiter", "Saturn"],
    userAnswer: "",
  },
  {
    id: 9,
    question: "What is the symbol for the chemical element 'Gold'?",
    answer: "Au",
    options: ["Go", "Gd", "Au", "Ag"],
    userAnswer: "",
  },
  {
    id: 10,
    question: "What is the largest organ in the human body?",
    answer: "Skin",
    options: ["Heart", "Brain", "Lungs", "Skin"],
    userAnswer: "",
  },
  {
    id: 11,
    question:
      "Which famous scientist developed the theory of general relativity?",
    answer: "Albert Einstein",
    options: [
      "Isaac Newton",
      "Marie Curie",
      "Albert Einstein",
      "Galileo Galilei",
    ],
    userAnswer: "",
  },
  {
    id: 12,
    question: "What is the smallest prime number?",
    answer: "2",
    options: ["1", "2", "3", "5"],
    userAnswer: "",
  },
  {
    id: 13,
    question: "In which year did World War II end?",
    answer: "1945",
    options: ["1918", "1939", "1945", "1955"],
    userAnswer: "",
  },
  {
    id: 14,
    question: "What is the national flower of India?",
    answer: "Lotus",
    options: ["Rose", "Tulip", "Sunflower", "Lotus"],
    userAnswer: "",
  },
  {
    id: 15,
    question: "What is the chemical symbol for water?",
    answer: "H2O",
    options: ["O2", "CO2", "H2O", "N2"],
    userAnswer: "",
  },
  // Add more questions here...
];

export default quizData;
